const fs=require('fs')
console.log('first line')
let data=fs.readFileSync('file1.txt')
console.log('data in file1 '+data)
let data1=fs.readFileSync('file2.txt')
console.log('data in file2 '+data1)
let data2=fs.readFileSync('file3.txt')
console.log('data in file3 '+data2)
console.log('end')